package template

const HTTP_CODE_VALID_REQUEST = 200
const HTTP_CODE_ENTITY_CREATED = 201
const HTTP_CODE_ENTITY_NOEXIST = 404
const HTTP_CODE_ENTITY_CONFLICT = 409
const HTTP_CODE_INVALID_REQUEST = 400
const HTTP_CODE_ACCESS_UNAUTHORIZED = 401
const HTTP_CODE_ACCESS_FORBIDDEN = 403
const HTTP_CODE_NOALLOWED_REQUEST = 405
const HTTP_CODE_TOOMANY_REQUEST = 429
const HTTP_CODE_SERVER_ERROR = 500
