package template

// HTTP ERROR CODES
const VALID_REQUEST = 200
const ENTITY_CREATED = 201
const ENTITY_NOEXIST = 404
const ENTITY_CONFLICT = 409
const INVALID_REQUEST = 400
const ACCESS_UNAUTHORIZED = 401
const ACCESS_FORBIDDEN = 403
const NOALLOWED_REQUEST = 405
const TOOMANY_REQUEST = 429
const SERVER_ERROR = 500
